Repository flairNLP/flair, pull requests merged in 2024-06, with the labels that each got.

#3426 datasets: add support for new Bavarian MaiBaam UD
  flair/datasets/__init__.py
  flair/datasets/treebanks.py
Labels: candidate for next release

#3470 load best model at end, even when there is no final evaluation
  flair/trainers/trainer.py
Labels: bug, candidate for next release

#3455 fix _all_scores_for_token in ViterbiDecoder
  flair/models/sequence_tagger_utils/viterbi.py
Labels: bug
